apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshd-jumphost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sshd-jumphost
  template:
    metadata:
      labels:
        app: sshd-jumphost
    spec:
      containers:
      - name: sshd-jumphost
        image: nickvanrompuy/sshd-jumphost:latest
        ports:
        - containerPort: 22
        volumeMounts:
            - mountPath: "/var/my-app"
              name: ssh-key-jumphost
              readOnly: true
      env:
        - name: SSH_USER_HOME
          value: "/path/to/your/custom/home"
      volumes:
        - name: ssh-key-jumphost
          secret:
            secretName: jumphost-private-key

---
apiVersion: v1
kind: Service
metadata:
  name: sshd-jumphost
spec:
  selector:
    app: sshd-jumphost
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
  type: NodePort
