
### In progress , do not use
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshd-jumphost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sshd-jumphost
  template:
    metadata:
      labels:
        app: sshd-jumphost
    spec:
      containers:
      - name: sshd-jumphost
        image: nick0tin/jumphost-ridethenet:latest
        ports:
        - containerPort: 22
        volumeMounts:
            - mountPath: "/etc/.secrets"
              name: ssh-key-jumphost
              readOnly: true
        env:
        - name: SSH_USER
          value: "ssh-agent"
        - name: SSH_PRIVATE_KEY_FILE
          value: "/etc/.secrets/ssh-key-jumphost"
      volumes:
        - name: ssh-key-jumphost
          secret:
            secretName: jumphost-private-key
      imagePullSecrets:
        - name: registrykey-dockerhub-nick0tin    

---
apiVersion: v1
kind: Service
metadata:
  name: sshd-jumphost
spec:
  selector:
    app: sshd-jumphost
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
  type: NodePort
